package bundle

import (
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/okfcli/okf/internal/concept"
	"github.com/okfcli/okf/internal/index"
)

func TestLoad_ValidBundle(t *testing.T) {
	b, err := Load("../../testdata/valid")
	if err != nil {
		t.Fatalf("Load failed: %v", err)
	}
	// 3 concept documents (ga4, events_, freshness).
	if len(b.Concepts) != 3 {
		t.Fatalf("got %d concepts, want 3", len(b.Concepts))
	}
	// Check concept IDs are derived correctly.
	wantIDs := map[string]bool{
		"datasets/ga4":        false,
		"tables/events_":      false,
		"playbooks/freshness": false,
	}
	for _, c := range b.Concepts {
		if _, ok := wantIDs[c.ID]; !ok {
			t.Errorf("unexpected concept ID: %s", c.ID)
		}
		wantIDs[c.ID] = true
	}
	for id, found := range wantIDs {
		if !found {
			t.Errorf("missing concept: %s", id)
		}
	}
}

func TestLoad_HasConcept(t *testing.T) {
	b, err := Load("../../testdata/valid")
	if err != nil {
		t.Fatalf("Load failed: %v", err)
	}
	if !b.HasConcept("tables/events_") {
		t.Error("HasConcept(tables/events_) = false, want true")
	}
	if b.HasConcept("nonexistent") {
		t.Error("HasConcept(nonexistent) = true, want false")
	}
}

func TestLoad_HasReserved(t *testing.T) {
	tmp := t.TempDir()

	subDir := filepath.Join(tmp, "sub")
	if err := os.MkdirAll(subDir, 0o755); err != nil {
		t.Fatalf("mkdir sub: %v", err)
	}
	if err := os.WriteFile(filepath.Join(subDir, "index.md"), []byte("# Sub index\n"), 0o644); err != nil {
		t.Fatalf("write index: %v", err)
	}

	b, err := Load(tmp)
	if err != nil {
		t.Fatalf("Load failed: %v", err)
	}
	if !b.HasReserved("sub/index") {
		t.Error("HasReserved(sub/index) = false, want true")
	}
	if b.HasReserved("sub/log") {
		t.Error("HasReserved(sub/log) = true, want false")
	}
	if b.HasReserved("nonexistent") {
		t.Error("HasReserved(nonexistent) = true, want false")
	}
}

func TestLoad_FrontmatterParsed(t *testing.T) {
	b, err := Load("../../testdata/valid")
	if err != nil {
		t.Fatalf("Load failed: %v", err)
	}
	c := b.Get("datasets/ga4")
	if c == nil {
		t.Fatal("concept datasets/ga4 not found")
	}
	if c.Frontmatter.Type != "BigQuery Dataset" {
		t.Errorf("type = %q, want 'BigQuery Dataset'", c.Frontmatter.Type)
	}
	if c.Frontmatter.Title != "GA4 Ecommerce" {
		t.Errorf("title = %q, want 'GA4 Ecommerce'", c.Frontmatter.Title)
	}
	if len(c.Frontmatter.Tags) != 3 {
		t.Errorf("tags len = %d, want 3", len(c.Frontmatter.Tags))
	}
}

// TestLoad_ReservedIndexNoFrontmatter verifies that a reserved index.md file
// without YAML frontmatter (as generated by `okf index`) is still loaded into
// Reserved with a correct ID, Path, and raw Body content.
func TestLoad_ReservedIndexNoFrontmatter(t *testing.T) {
	tmp := t.TempDir()

	// Write a concept file with frontmatter so the bundle is non-empty.
	conceptDir := filepath.Join(tmp, "tables")
	if err := os.MkdirAll(conceptDir, 0o755); err != nil {
		t.Fatalf("mkdir tables: %v", err)
	}
	conceptContent := "---\ntype: BigQuery Table\ntitle: Events\n---\n\nEvent data.\n"
	if err := os.WriteFile(filepath.Join(conceptDir, "events_.md"), []byte(conceptContent), 0o644); err != nil {
		t.Fatalf("write concept: %v", err)
	}

	// Write an index.md WITHOUT frontmatter (as `okf index` generates).
	indexPath := filepath.Join(conceptDir, "index.md")
	indexContent := "# Index\n\n- [events_](events_.md)\n"
	if err := os.WriteFile(indexPath, []byte(indexContent), 0o644); err != nil {
		t.Fatalf("write index: %v", err)
	}

	b, err := Load(tmp)
	if err != nil {
		t.Fatalf("Load failed: %v", err)
	}

	var found *concept.Concept
	for _, r := range b.Reserved {
		if r.ID == "tables/index" {
			found = r
			break
		}
	}
	if found == nil {
		t.Fatalf("expected Reserved to contain tables/index, got %d entries", len(b.Reserved))
	}

	// Path should be the absolute path to index.md.
	absIndex, _ := filepath.Abs(indexPath)
	if found.Path != absIndex {
		t.Errorf("Path = %q, want %q", found.Path, absIndex)
	}

	// Body should contain the raw file content.
	if found.Body != indexContent {
		t.Errorf("Body = %q, want %q", found.Body, indexContent)
	}
}

// TestLoad_GeneratedIndexIsDiscoverable is an end-to-end regression test for
// the user-visible symptom: after `okf index` generates index.md files (which
// have no frontmatter), reloading the bundle must expose them in b.Reserved so
// runIndex reports a non-empty indexes_written. Previously these files were
// silently dropped and the index command reported zero indexes.
func TestLoad_GeneratedIndexIsDiscoverable(t *testing.T) {
	tmp := t.TempDir()

	conceptDir := filepath.Join(tmp, "tables")
	if err := os.MkdirAll(conceptDir, 0o755); err != nil {
		t.Fatalf("mkdir tables: %v", err)
	}
	conceptContent := "---\ntype: BigQuery Table\ntitle: Events\n---\n\nEvent data.\n"
	if err := os.WriteFile(filepath.Join(conceptDir, "events_.md"), []byte(conceptContent), 0o644); err != nil {
		t.Fatalf("write concept: %v", err)
	}

	// Generate index.md files the same way `okf index` does.
	if err := index.Generate(tmp); err != nil {
		t.Fatalf("index.Generate: %v", err)
	}

	b, err := Load(tmp)
	if err != nil {
		t.Fatalf("Load failed: %v", err)
	}

	// Mirror runIndex's collection logic.
	var indexFiles []string
	for _, r := range b.Reserved {
		if r.ID == "index" || strings.HasSuffix(r.ID, "/index") {
			indexFiles = append(indexFiles, r.Path)
		}
	}
	if len(indexFiles) == 0 {
		t.Fatalf("expected at least one generated index in Reserved, got %d reserved entries", len(b.Reserved))
	}

	// The tables/ subdirectory index must be among them and carry its body.
	var tablesIndex *concept.Concept
	for _, r := range b.Reserved {
		if r.ID == "tables/index" {
			tablesIndex = r
			break
		}
	}
	if tablesIndex == nil {
		t.Fatal("expected Reserved to contain tables/index")
	}
	if tablesIndex.Body == "" {
		t.Error("generated index Body is empty, want raw index content")
	}
}

// Issue #27: a .md file that is not a concept must fail with an error that
// names the file and the reason, distinguishable from a filesystem failure.
func TestLoad_MissingFrontmatterNamesFile(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "index.md"), []byte("# Demo\n"), 0644); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(filepath.Join(dir, "docs"), 0755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "docs", "README.md"), []byte("# Demo project\n"), 0644); err != nil {
		t.Fatal(err)
	}

	_, err := Load(dir)
	if err == nil {
		t.Fatal("expected an error for markdown without frontmatter")
	}
	var pe *ParseError
	if !errors.As(err, &pe) {
		t.Fatalf("error %T %q is not a *ParseError", err, err)
	}
	if pe.Path != "docs/README.md" {
		t.Errorf("ParseError.Path = %q, want docs/README.md", pe.Path)
	}
	if !errors.Is(err, concept.ErrNoFrontmatter) {
		t.Errorf("error does not unwrap to ErrNoFrontmatter: %v", err)
	}
	for _, want := range []string{"docs/README.md", "no YAML frontmatter"} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("error %q does not mention %q", err, want)
		}
	}
}

func TestLoad_UnclosedFrontmatterIsParseError(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "a.md"), []byte("---\ntype: T\n\nbody"), 0644); err != nil {
		t.Fatal(err)
	}
	_, err := Load(dir)
	var pe *ParseError
	if !errors.As(err, &pe) || pe.Path != "a.md" {
		t.Fatalf("want *ParseError for a.md, got %T %v", err, err)
	}
}

func TestLoad_HiddenFilesSkipped(t *testing.T) {
	// Hidden directories are already skipped; hidden files (editor drafts,
	// backups) get the same treatment rather than taking the bundle down.
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "a.md"), []byte("---\ntype: T\n---\n\nbody"), 0644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, ".draft.md"), []byte("# not a concept\n"), 0644); err != nil {
		t.Fatal(err)
	}
	b, err := Load(dir)
	if err != nil {
		t.Fatalf("Load failed: %v", err)
	}
	if len(b.Concepts) != 1 || b.Concepts[0].ID != "a" {
		t.Fatalf("got concepts %+v, want just a", b.Concepts)
	}
}
