package bundle

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/okfcli/okf/internal/concept"
)

func TestLoad_ValidBundle(t *testing.T) {
	b, err := Load("../../testdata/valid")
	if err != nil {
		t.Fatalf("Load failed: %v", err)
	}
	// 3 concept documents (ga4, events_, freshness).
	if len(b.Concepts) != 3 {
		t.Fatalf("got %d concepts, want 3", len(b.Concepts))
	}
	// Check concept IDs are derived correctly.
	wantIDs := map[string]bool{
		"datasets/ga4":       false,
		"tables/events_":     false,
		"playbooks/freshness": false,
	}
	for _, c := range b.Concepts {
		if _, ok := wantIDs[c.ID]; !ok {
			t.Errorf("unexpected concept ID: %s", c.ID)
		}
		wantIDs[c.ID] = true
	}
	for id, found := range wantIDs {
		if !found {
			t.Errorf("missing concept: %s", id)
		}
	}
}

func TestLoad_HasConcept(t *testing.T) {
	b, err := Load("../../testdata/valid")
	if err != nil {
		t.Fatalf("Load failed: %v", err)
	}
	if !b.HasConcept("tables/events_") {
		t.Error("HasConcept(tables/events_) = false, want true")
	}
	if b.HasConcept("nonexistent") {
		t.Error("HasConcept(nonexistent) = true, want false")
	}
}

func TestLoad_FrontmatterParsed(t *testing.T) {
	b, err := Load("../../testdata/valid")
	if err != nil {
		t.Fatalf("Load failed: %v", err)
	}
	c := b.Get("datasets/ga4")
	if c == nil {
		t.Fatal("concept datasets/ga4 not found")
	}
	if c.Frontmatter.Type != "BigQuery Dataset" {
		t.Errorf("type = %q, want 'BigQuery Dataset'", c.Frontmatter.Type)
	}
	if c.Frontmatter.Title != "GA4 Ecommerce" {
		t.Errorf("title = %q, want 'GA4 Ecommerce'", c.Frontmatter.Title)
	}
	if len(c.Frontmatter.Tags) != 3 {
		t.Errorf("tags len = %d, want 3", len(c.Frontmatter.Tags))
	}
}

// TestLoad_ReservedIndexNoFrontmatter verifies that a reserved index.md file
// without YAML frontmatter (as generated by `okf index`) is still loaded into
// Reserved with a correct ID, Path, and raw Body content.
func TestLoad_ReservedIndexNoFrontmatter(t *testing.T) {
	tmp := t.TempDir()

	// Write a concept file with frontmatter so the bundle is non-empty.
	conceptDir := filepath.Join(tmp, "tables")
	if err := os.MkdirAll(conceptDir, 0o755); err != nil {
		t.Fatalf("mkdir tables: %v", err)
	}
	conceptContent := "---\ntype: BigQuery Table\ntitle: Events\n---\n\nEvent data.\n"
	if err := os.WriteFile(filepath.Join(conceptDir, "events_.md"), []byte(conceptContent), 0o644); err != nil {
		t.Fatalf("write concept: %v", err)
	}

	// Write an index.md WITHOUT frontmatter (as `okf index` generates).
	indexPath := filepath.Join(conceptDir, "index.md")
	indexContent := "# Index\n\n- [events_](events_.md)\n"
	if err := os.WriteFile(indexPath, []byte(indexContent), 0o644); err != nil {
		t.Fatalf("write index: %v", err)
	}

	b, err := Load(tmp)
	if err != nil {
		t.Fatalf("Load failed: %v", err)
	}

	var found *concept.Concept
	for _, r := range b.Reserved {
		if r.ID == "tables/index" {
			found = r
			break
		}
	}
	if found == nil {
		t.Fatalf("expected Reserved to contain tables/index, got %d entries", len(b.Reserved))
	}

	// Path should be the absolute path to index.md.
	absIndex, _ := filepath.Abs(indexPath)
	if found.Path != absIndex {
		t.Errorf("Path = %q, want %q", found.Path, absIndex)
	}

	// Body should contain the raw file content.
	if found.Body != indexContent {
		t.Errorf("Body = %q, want %q", found.Body, indexContent)
	}
}
